# Generated by Django 6.0.2 on 2026-02-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Токен для подтверждения email.",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Токен подтверждения",
            ),
        ),
    ]
