# Generated by Django 6.0.2 on 2026-02-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_user_list", "Может просматривать список пользователей"),
                    ("can_block_users", "Может блокировать пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите страну.",
                max_length=100,
                null=True,
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона.",
                max_length=20,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
