# Generated by Django 6.0.2 on 2026-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату и время попытки отправки.",
                        verbose_name="Дата и время попытки отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        help_text="Введите ответ почтового сервера.",
                        verbose_name=" Ответ почтового сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время начала отправки.",
                        verbose_name="Дата и время начала отправки",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время окончания отправки.",
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="Создана",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Напишите тему письма.",
                        max_length=250,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Добавьте содержимое письма.",
                        verbose_name="Содержание письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Введите ваши ФИО.",
                        max_length=150,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Введите ваш email.",
                        max_length=150,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Введите ваш комментарий.", verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
