# Generated by Django 6.0.2 on 2026-02-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailing_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Введите ваши ФИО.",
                max_length=150,
                null=True,
                verbose_name="ФИО",
            ),
        ),
    ]
