# Generated by Django 6.0.2 on 2026-02-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_recipient_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Введите ваш комментарий.",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
    ]
