# Generated by Django 6.0.2 on 2026-02-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_recipient_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                blank=True,
                default="Создана",
                max_length=50,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
